"""initial_schema

Revision ID: 57fe12d76cd3
Revises: 
Create Date: 2026-08-12 22:22:35.477569
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fe12d76cd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_metrics',
    sa.Column('baseline_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('avg_resolution_minutes', sa.Float(), nullable=False),
    sa.Column('human_help_rate', sa.Float(), nullable=False),
    sa.Column('avg_eta_error_minutes', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('baseline_id')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('party_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('facility_id', sa.String(length=32), nullable=True),
    sa.Column('shipment_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('carrier_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('home_base', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_table('facilities',
    sa.Column('facility_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('open_time', sa.String(length=8), nullable=False),
    sa.Column('close_time', sa.String(length=8), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('carrier_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=False),
    sa.Column('length_ft', sa.Integer(), nullable=False),
    sa.Column('refrigeration_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('docks',
    sa.Column('dock_id', sa.String(length=32), nullable=False),
    sa.Column('facility_id', sa.String(length=32), nullable=False),
    sa.Column('dock_name', sa.String(length=64), nullable=False),
    sa.Column('supported_vehicle_type', sa.String(length=64), nullable=False),
    sa.Column('supported_product_class', sa.String(length=64), nullable=False),
    sa.Column('max_length_ft', sa.Integer(), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('dock_id')
    )
    op.create_table('facility_rules',
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('facility_id', sa.String(length=32), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.String(length=8), nullable=True),
    sa.Column('effective_to', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('scheduling_runs',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('facility_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('objective', sa.String(length=120), nullable=False),
    sa.Column('input_snapshot_json', sa.Text(), nullable=False),
    sa.Column('proposal_json', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('driver_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('origin_id', sa.String(length=32), nullable=False),
    sa.Column('destination_id', sa.String(length=32), nullable=False),
    sa.Column('product_class', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('planned_eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_unload_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('leave_by', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('appointment_slots',
    sa.Column('slot_id', sa.String(length=32), nullable=False),
    sa.Column('facility_id', sa.String(length=32), nullable=False),
    sa.Column('dock_id', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('slot_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.dock_id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('driver_exceptions',
    sa.Column('exception_id', sa.String(length=32), nullable=False),
    sa.Column('driver_id', sa.String(length=32), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('exception_type', sa.String(length=64), nullable=False),
    sa.Column('reported_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('latest_declared_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conversation_state', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('exception_id')
    )
    op.create_table('eta_updates',
    sa.Column('eta_update_id', sa.String(length=32), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('declared_eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('eta_update_id')
    )
    op.create_table('facility_checkins',
    sa.Column('checkin_id', sa.String(length=32), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('facility_id', sa.String(length=32), nullable=False),
    sa.Column('gate_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_status', sa.String(length=32), nullable=False),
    sa.Column('queue_status', sa.String(length=32), nullable=False),
    sa.Column('dock_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_finish_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('checkin_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.String(length=32), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('slot_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.slot_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('case_metrics',
    sa.Column('metric_id', sa.String(length=32), nullable=False),
    sa.Column('exception_id', sa.String(length=32), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('options_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('human_intervention', sa.Boolean(), nullable=False),
    sa.Column('first_option_accepted', sa.Boolean(), nullable=True),
    sa.Column('eta_source_used', sa.String(length=32), nullable=True),
    sa.Column('predicted_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_gate_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_projected_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('new_projected_wait_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['driver_exceptions.exception_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('exception_id')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=32), nullable=False),
    sa.Column('exception_id', sa.String(length=32), nullable=False),
    sa.Column('sender_type', sa.String(length=32), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['driver_exceptions.exception_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('location_shares',
    sa.Column('location_id', sa.String(length=32), nullable=False),
    sa.Column('exception_id', sa.String(length=32), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['driver_exceptions.exception_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('option_views',
    sa.Column('view_id', sa.String(length=32), nullable=False),
    sa.Column('exception_id', sa.String(length=32), nullable=False),
    sa.Column('slot_id', sa.String(length=32), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['driver_exceptions.exception_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.slot_id'], ),
    sa.PrimaryKeyConstraint('view_id')
    )
    op.create_table('route_etas',
    sa.Column('route_eta_id', sa.String(length=32), nullable=False),
    sa.Column('exception_id', sa.String(length=32), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('route_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_for_scheduling', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['driver_exceptions.exception_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('route_eta_id')
    )
    op.create_table('slot_holds',
    sa.Column('hold_id', sa.String(length=32), nullable=False),
    sa.Column('exception_id', sa.String(length=32), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('slot_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['driver_exceptions.exception_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.slot_id'], ),
    sa.PrimaryKeyConstraint('hold_id'),
    sa.UniqueConstraint('hold_id', name='uq_hold_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_holds')
    op.drop_table('route_etas')
    op.drop_table('option_views')
    op.drop_table('location_shares')
    op.drop_table('chat_messages')
    op.drop_table('case_metrics')
    op.drop_table('appointments')
    op.drop_table('facility_checkins')
    op.drop_table('eta_updates')
    op.drop_table('driver_exceptions')
    op.drop_table('appointment_slots')
    op.drop_table('shipments')
    op.drop_table('scheduling_runs')
    op.drop_table('facility_rules')
    op.drop_table('docks')
    op.drop_table('vehicles')
    op.drop_table('facilities')
    op.drop_table('drivers')
    op.drop_table('contacts')
    op.drop_table('baseline_metrics')
    # ### end Alembic commands ###
